name: Generate topic list

on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
      - uses: mikefarah/yq@master

      - name: Install CPAN required modules
        run: cpanm HTML::Parser

      - name: Download feed.xml
        uses: wei/curl@master
        with:
          args: -s https://minkorrekt.podigee.io/feed/mp3 -o feed.xml

      - name: Pre-process feed.xml
        run: |
          xpath -n -q -e 'rss/channel/item/title | rss/channel/item/content:encoded/text() | rss/channel/item/pubDate | rss/channel/item/link' feed.xml | \
          perl -C -MHTML::Entities -pe 'decode_entities($_);decode_entities($_);' > preprocessed.txt

      - name: Generate minkorrekt-themen.unfiltered.yaml
        run: |
          cat preprocessed.txt | \
          perl -C -pe 's/\"/\\\"/g;s/<title>([^<]+)<\/title>/- title: "$1"/g;s/<(pubDate|link)>([^<]+)<\/\1>/  $1: "$2"/g;s/<[^>]+>//g;s/^\h*?Thema ([1-4]):?\h*?(?:\\\"|[\x{201C}\x{201D}\x{201E}])(.+?)(?:\\\".*$|\h*?[\x{201C}\x{201D}\x{201E}].*$|\h\x{2013}[^\x{201C}\x{201D}\x{201E}\v]*$)/  topic$1: "$2"/;s/^(?!  topic[1-4]:|- title:|  pubDate:|  link).*?$//gi;s/^\s*$//' | \
          yq e '[.[]]' - > minkorrekt-themen.unfiltered.yaml

      - name: Generate minkorrekt-themen.yaml
        run: yq e '[.[] | select(has("topic1") // has("topic2") // has("topic3") // has("topic4"))]' minkorrekt-themen.unfiltered.yaml > minkorrekt-themen.yaml

      - name: Generate minkorrekt-themen.full.yaml
        run: |
          cat preprocessed.txt | \
          perl -C -pe 's/\"/\\\"/g;s/<title>([^<]+)<\/title>/- title: "$1"/g;s/<(pubDate|link)>([^<]+)<\/\1>/  $1: "$2"/g;s/<[^>]+>//g;s/^\h*?(Thema ([1-4]):?.*$)/  topic$2: "$1"/;s/^(?!  topic[1-4]:|- title:|  pubDate:|  link).*?$//gi;s/^\s*$//' | \
          yq e '[.[]]' - > minkorrekt-themen.full.yaml

      - name: Cleanup
        run: rm feed.xml preprocessed.txt

      - name: Commit updated files
        run: |
          git config --global user.name 'M!Topics Action'
          git config --global user.email 'mtopics-action@tintenwolf.de'
          git add *.yaml
          git commit -m "Updated files from feed"
          git push
